name = "Integrals"
uuid = "dbdf9ee0-7e86-4d79-a131-ad1b41ae593a"
authors = ["paolo-di-simone <72343829+paolo-di-simone@users.noreply.github.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearAlgebraicRepresentation = "95167b0c-186a-594b-a231-52369c6de044"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
